### ISSUE TITLE
Node 12 issue

### ISSUE THREAD

**Issue by kylehotchkiss** [wildbit/postmark.js#49]
Getting this 

```
TypeError: this.verifyToken is not a function
    at Object.BaseClient (/Sites/domain.tld/tasks/project/node_modules/postmark/dist/client/BaseClient.js:22:14)
    at Object.ServerClient (/Sites/domain.tld/tasks/project/node_modules/postmark/dist/client/ServerClient.js:28:23)
    at Object.module.exports [as func] (/Sites/domain.tld/tasks/project/daily-update.js:8:29)
    at /Sites/domain.tld/index.js:40:24
    at Layer.handle [as handle_request] (/Sites/domain.tld/node_modules/express/lib/router/layer.js:95:5)
    at next (/Sites/domain.tld/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Sites/domain.tld/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Sites/domain.tld/node_modules/express/lib/router/layer.js:95:5)
    at /Sites/domain.tld/node_modules/express/lib/router/index.js:281:22
    at param (/Sites/domain.tld/node_modules/express/lib/router/index.js:354:14)
```

when using the setup guide on `https://account.postmarkapp.com/servers/%my id%/get_started` like the below, with Node 12.

```
// Require:
var postmark = require("postmark");

// Send an email:
var client = new postmark.ServerClient("x");

client.sendEmail({
  "From": "sender@example.org",
  "To": "x",
  "Subject": "Test",
  "TextBody": "Hello from Postmark!"
});
```

Issue was temporarily resolved by switching to Node 10 in my project.

**Comment by ibalosh** [comment]
Hi @kylehotchkiss 

thank you for reporting this, I will see to check it out soon

**Comment by kylehotchkiss** [comment]
Hi Ibalosh, I seem to be incorrect on this working after switching to node 10. I commented out `this.verifyToken()` in the compiled code in node_modules/postmark/dist/index.js (I think)

Let me know if I can provide further details on my environment to help you debug.

I am just using the HTTP API with Axios for the time being which is working excellent for me.

**Comment by ibalosh** [comment]
Hi @kylehotchkiss 

could you share the exact versions of node you used (for both 10 and 12)? We have test coverage up to version 10 and haven't seen this issue yet.

**Comment by kylehotchkiss** [comment]
10.15.0 & 12.1.0

**Comment by atheken** [comment]
@kylehotchkiss -- are you running node with any special interpreter flags (i.e. `--harmony`)? We're building from Typescript, and so `this` scoping should be pretty much bulletproof by the time it's transpiled and executed by node.
