### ISSUE TITLE
verifyToken is not a function

### ISSUE THREAD

**Issue by period** [wildbit/postmark.js#54]
Same issue as found in #49 

Having the same issue. I'm using the code examples section found on the template I created (i.e. postmark.sendEmailWithTemplate).

root@vps102313:~# node --version
v9.7.1

Ubuntu 16

/root/acorn-autoclaim/node_modules/postmark/dist/client/BaseClient.js:22
        this.verifyToken(token);
             ^

TypeError: this.verifyToken is not a function
    at Object.BaseClient (/root/acorn-autoclaim/node_modules/postmark/dist/client/BaseClient.js:22:14)
    at Object.ServerClient (/root/acorn-autoclaim/node_modules/postmark/dist/client/ServerClient.js:28:23)
    at Object.<anonymous> (/root/acorn-autoclaim/index.js:6:42)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)

**Comment by period** [comment]
Fixed it. I was using ``new require("postmark").ServerClient("api key")`` as a shortcut. Splitting the require worked.
