### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by crow1796** [wildbit/postmark.js#76]
I'm getting this error in my prod server.

I'm using DigitalOcean
Ubuntu 20.04
NodeJS 12.18.1
Postmark 2.6.1

here's the error:
```
/home/circleci/myproject/node_modules/postmark/dist/client/BaseClient.js:22
        this.token = token.trim();
                           ^

TypeError: Cannot read property 'trim' of undefined
    at ServerClient.BaseClient (/home/circleci/myproject/node_modules/postmark/dist/client/BaseClient.js:22:28)
    at new ServerClient (/home/circleci/myproject/node_modules/postmark/dist/client/ServerClient.js:28:23)
    at Object.<anonymous> (/home/circleci/myproject/build/utils/postmark-client.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/circleci/myproject/build/schema/admin.js:22:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by crow1796** [comment]
I'm gonna close this now, it turned out that I just missed 1 character in my access token.

**Comment by olso** [comment]
@crow1796 I also just ran into this, on gitlab ci, just set the empty variables to something like 'xxx'
