### ISSUE TITLE
TemplateModel not marked as required

### ISSUE THREAD

**Issue by tjokimie** [wildbit/postmark.js#80]
**Actual behaviour:**

Sending email with template using `sendEmailWithTemplate` without `TemplateModel` fails due to:

```
ApiInputError: A 'TemplateModel' is required when using a template to send an email.
    at ErrorHandler.buildRequestErrorByStatus (/workspace/node_modules/postmark/dist/client/ErrorHandler.js:70:24)
    at ErrorHandler.buildErrorForResponse (/workspace/node_modules/postmark/dist/client/ErrorHandler.js:51:21)
    at ErrorHandler.buildRequestError (/workspace/node_modules/postmark/dist/client/ErrorHandler.js:21:25)
    at /workspace/node_modules/postmark/dist/client/BaseClient.js:102:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.sendLoginNotFoundEmail (/workspace/dist/lib/mailer/index.js:96:3)
    at async login (/workspace/dist/app/api/public/login.js:54:7)
```

However in the types `TemplateModel` is marked as optional inside `template`: https://github.com/wildbit/postmark.js/blob/c8b063b1148683c6a3ca7d50605cc20fb1521a25/src/client/ServerClient.ts#L129

**Expected behaviour:**

I would expect the types to safeguard me from doing mistakes like this. Thus I would expect `TemplateModel` to be required in the types.

**Comment by ibalosh** [comment]
We have fixed this issue in version 2.7.6
